Remove publication_type_id and all associated searches
We think this is causing a problem with Elastic Search.
This does mean we can't search by publication type but having
somewhat-functional search feels like a bonus right now.

Plus, if this works, it's useful diagnostic information.

I can't reproduce the issue locally, even when using elasticsearch
with an imported copy of the database.

https://github.com/wagtail/wagtail/issues/3728 has the same
error:

prefix = definition_model._meta.app_label.lower() + '_' + definition_model.__name__.lower() + '__'
AttributeError: 'NoneType' object has no attribute '_meta'

and looks like it's got the same conflict between "need index to
make something work" and "search_fields contains non-existent field"