Wagtail 3: fix menu-fixtures null values
core.tests.TestFrontendTags' (and other classes) setup hits issues with null PageLogEntry fields:

sqlite3.IntegrityError: NOT NULL constraint failed: wagtailcore_pagelogentry.data
django.db.utils.IntegrityError: Problem installing fixture '/app/fixtures/menu-fixtures.json': Could not load wagtailcore.PageLogEntry(pk=2): NOT NULL constraint failed: wagtailcore_pagelogentry.data

Using
jq '(.[] | select(.model == "wagtailcore.pagelogentry" and .fields.data == null)).fields.data |= {}' menu-fixtures.json > menu-fixtures2.json
replaces them with empty dictionaries.

This commit was generated with
`git diff -w | git apply --cached --ignore-whitespace`
to not generate a vast diff due to spacing differences between `dumpdata` and `jq`.